version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8088:8088"  # Mở port cho ứng dụng FastAPI
    depends_on:
      - mongodb
      - redis
    environment:
      - MAIN_PORT=${MAIN_PORT}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
    volumes:
      - ./src:/app  # Mount thư mục mã nguồn vào container

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27026:27017"  # Port custom cho MongoDB
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "27027:6379"  # Port custom cho Redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--port", "6379"]
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
